Repository weechat/scripts, pull requests merged in 2020-10, with the labels that each got.

#429 arespond.py 0.1.1: added py3 support
  python/arespond.py
Labels: bug, python3

#431 leet.py 0.2: Added support of python3 while retaining support of python2
  python/leet.py
Labels: python3

#432 autosort.py 3.9: Remove buffers.pl from recommended settings.
  python/autosort.py
Labels: doc

#434 confversion.py 0.3: Adapt to python 3
  python/confversion.py
Labels: python3

#436 grep.py: Fix Python 3 issue reversing range
  python/grep.py
Labels: python3, waiting info
