Repository weechat/scripts, pull requests merged in 2020-05, with the labels that each got.

#409 slack.py 2.6.0: Merge with mainline
  python/slack.py
Labels: feature

#408 grep.py 0.8.3: more python3 compatibility fixes
  python/grep.py
Labels: bug

#399 buffer_dmenu.py 0.1.2: Add Python 3 support
  python/buffer_dmenu.py
Labels: python3
