Repository weechat/scripts, pull requests merged in 2021-10, with the labels that each got.

#461 chanmon.pl 2.7: Make tags configurable
  perl/chanmon.pl
Labels: feature

#466 weenotifier.py: notifier using IrssiNotifier
  python/weenotifier.py
Labels: new script

#470 fish.py 0.9.7: utf-8 encode key passed to blowfish
  python/fish.py
Labels: bug
