Repository weechat/scripts, pull requests merged in 2022-11, with the labels that each got.

#507 New script read_marker.py: draft/read-marker extension support
  python/read_marker.py
Labels: new script

#508 soju.py 0.3.0: remove soju.im/read support
  python/soju.py
Labels: feature

#514 slack.py 2.9.1: Merge with mainline
  python/slack.py
Labels: bug

#515 colorize_nicks.py 30: added "[:,]" to VALID_NICK
  python/colorize_nicks.py
Labels: bug

#516 openbsd_privdrop.py 0.1.1: sane defaults for unveil
  python/openbsd_privdrop.py
Labels: bug
